name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - name: Install Dependencies
        run: |
          uv pip install '.[dev]'
      - name: Run Ruff
        run: ruff check .
      - name: Run Ruff Format
        run: ruff format --check .
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9, "3.10"]
        django-version: [3.2, 4.0, 4.1, 4.2]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - name: Install Dependencies
        run: |
          uv pip install "Django==${{ matrix.django-version }}.*"
          uv pip install -e '.[test]'
      - name: Run Tests
        run: |
          uv run pytest django_modal_actions/tests
